import { X, Shield, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface LegalModalProps {
  isOpen: boolean;
  type: 'tos' | 'privacy';
  onClose: () => void;
}

export function LegalModal({ isOpen, type, onClose }: LegalModalProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md">
          <div className="absolute inset-0 cursor-default" onClick={onClose} />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 10 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 10 }}
            className="w-full max-w-2xl max-h-[85vh] overflow-hidden rounded-2xl border border-neutral-900 bg-[#0d0d0e] shadow-2xl relative z-10 font-sans flex flex-col"
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-neutral-900 px-6 py-4.5 select-none shrink-0 bg-neutral-950/60">
              <div className="flex items-center gap-2.5">
                {type === 'tos' ? (
                  <FileText className="w-4.5 h-4.5 text-indigo-400" />
                ) : (
                  <Shield className="w-4.5 h-4.5 text-emerald-400" />
                )}
                <h3 className="text-sm font-bold text-white tracking-tight">
                  {type === 'tos' ? 'Terms of Service — Aura Workspace' : 'Privacy Policy — Aura Workspace'}
                </h3>
              </div>
              <button
                onClick={onClose}
                className="rounded-lg p-1 hover:bg-neutral-900 text-neutral-400 hover:text-white cursor-pointer select-none transition-colors border border-transparent hover:border-neutral-800"
                type="button"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Modal Body Scroll Container */}
            <div className="flex-1 overflow-y-auto px-6 py-5 select-text text-neutral-300 text-xs leading-normal space-y-4 font-normal scrollbar-thin">
              {type === 'tos' ? (
                <>
                  <section className="space-y-1.5 animate-in fade-in duration-300">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">1. Acceptance of Terms</h4>
                    <p>
                      By accessing or using the Aura Workspace ("the Client", "re-branded ChatGPT Interface"), you agree to be bound by these Terms of Service. If you do not agree to any of these terms, please stop accessing or using the client immediately.
                    </p>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">2. AI-Generated Output & Refusal of Warranty</h4>
                    <p className="border-l-2 border-indigo-500/30 pl-3 text-neutral-400">
                      <strong>IMPORTANT:</strong> Aura Workspace provides proxy routing to third-party artificial intelligence engines (such as OpenRouter free LLMs, NVIDIA NIM evaluation models, and Groq high-speed pipelines). Output generated by artificial intelligence models may be factually incorrect, incomplete, delayed, or hallucinated. Aura Workspace and its contributors provide zero warranty, representations, or claims regarding output accuracy, completeness, safety, or suitability for critical tasks. You should evaluate and test code or copy comprehensively before using in professional settings.
                    </p>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">3. Acceptable Use Policy</h4>
                    <p>
                      You are strictly prohibited from utilizing the workspace to:
                    </p>
                    <ul className="list-disc list-inside pl-2 space-y-1 text-neutral-400">
                      <li>Generate spam, malicious software, malware, or phishing campaigns.</li>
                      <li>Produce hateful, harassing, unlawful, or copyright-violating answers.</li>
                      <li>Impersonate individuals or misrepresent AI-generated content as purely human-written.</li>
                      <li>Bypass, overload, or reverse engineer rate limit parameters of the upstream proxy endpoints.</li>
                    </ul>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">4. Provider Term Compliance</h4>
                    <p>
                      This workspace operates as an API routing proxy forwarding payload packets to model providers. Your usage of distinct models must comply with:
                    </p>
                    <ul className="list-disc list-inside pl-2 space-y-1 text-neutral-400">
                      <li>The <strong>OpenRouter Terms of Service</strong> regarding API usage.</li>
                      <li>The <strong>NVIDIA NIM Community Agreement</strong> (strictly restricting free evaluation tiers from commercial production abuse).</li>
                      <li>The <strong>Groq API Usage Criteria</strong> (including standard daily rate limits & quota throttling guidelines).</li>
                    </ul>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">5. Age Guidelines</h4>
                    <p>
                      Aura Workspace is strictly intended for users who are at least 13 years of age, or 18 years of age depending on distinct model vendor guidelines. If you are under the required age threshold, please discontinue use.
                    </p>
                  </section>

                  <section className="space-y-1.5 pb-2">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">6. Limitation of Liability</h4>
                    <p>
                      In no event shall Aura Workspace, its developers, or its sponsors be held liable for any indirect, incidental, direct, consequential, special, or exemplary damages, including but not limited to loss of data, profit losses, server downtime, system outages, or business interruptions stemming from model output hallucinations.
                    </p>
                  </section>
                </>
              ) : (
                <>
                  <section className="space-y-1.5 animate-in fade-in duration-300">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">1. Data Minimization & Privacy-First Architecture</h4>
                    <p>
                      Aura Workspace is styled with a local-first, privacy-respecting design framework. **We do not collect, store, or monitor your conversation history on any remote backend database.**
                    </p>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">2. Client-Side Local Storage Policy</h4>
                    <p>
                      Your active thread histories, parameters configurations, systems state, and active sessions are stored locally in your browser's persistent key-value mechanism (standard <code>localStorage</code> / <code>IndexedDB</code>).
                    </p>
                    <p className="text-neutral-400">
                      Because these items remain exclusively on your local device, clearing your desktop browser history or browser storage will permanently remove your session threads. Please back up critical texts manually.
                    </p>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">3. Third-Party Data Transit Pipelines</h4>
                    <p>
                      When you submit prompts inside the client:
                    </p>
                    <ol className="list-decimal list-inside pl-2 space-y-1 text-neutral-400">
                      <li>The request is parsed through the secure local server proxy to append required system instructions and proxy authorization tokens securely.</li>
                      <li>Prompt fragments are safely transmitted and processed by our upstream inference models provider endpoints (including OpenRouter, NVIDIA, or Groq) depending on your selected active model routing.</li>
                      <li>Your information is treated in accordance with distinct provider Privacy Policies. No proprietary client secrets are ever shared with unauthorized external trackers or advertising agencies.</li>
                    </ol>
                  </section>

                  <section className="space-y-1.5">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">4. Direct API Key Preservation</h4>
                    <p>
                      If you provide custom system developer keys as environment variables or inside the cloud platform, these keys are treated securely inside Node server configurations. They are **never** exposed to the browser.
                    </p>
                  </section>

                  <section className="space-y-1.5 pb-2">
                    <h4 className="text-[13px] font-bold text-white uppercase tracking-wide">5. Inquiries & Profile Links</h4>
                    <p>
                      For privacy inquiries or technical questions regarding client configurations, please connect directly with our engineering team via the safe LinkedIn link located at the bottom left-side menu index.
                    </p>
                  </section>
                </>
              )}
            </div>

            {/* Modal Footer */}
            <div className="border-t border-neutral-900 bg-neutral-950 px-6 py-4 flex items-center justify-end shrink-0">
              <button
                onClick={onClose}
                className="px-5 py-2 rounded-xl text-xs font-semibold bg-neutral-850 hover:bg-neutral-800 text-white cursor-pointer transition-colors border border-neutral-800"
                type="button"
              >
                Acknowledge & Close
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
